// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  // This installed Prisma version's config schema has no `directUrl` field.
  // DATABASE_URL (port 6543, transaction-mode pooler) is fine for runtime
  // queries. Migration commands must override DATABASE_URL with the Supabase
  // direct/session connection on port 5432, then use `prisma migrate status`
  // and `prisma migrate deploy`. Do not use `db push` for shared databases.
});
