// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
  // Runtime Prisma uses DATABASE_URL (port 6543 pooler). Prisma CLI migration
  // commands require DIRECT_URL (port 5432 direct/session connection) through
  // this config. There is deliberately no DATABASE_URL fallback: migration
  // commands must never reach the transaction pooler by accident.
});
