// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  // This installed Prisma version's config schema has no `directUrl` field.
  // DATABASE_URL (port 6543, transaction-mode pooler) is fine for the app's
  // own queries, but `db push`/`migrate dev` hang against it — Supabase's
  // pooler doesn't support the protocol Prisma's schema engine needs. Run
  // schema-changing commands with an explicit override instead:
  //   npx prisma db push --url="$DIRECT_URL"   (DIRECT_URL = session pooler, port 5432)
});
